shinyServer(function(input, output) {

  output$heatmap <- renderPlot({
    
    # Heatmap ---------------------------------------------- #
    fb <- fb[(fb$Post.Weekday %in% input$fb.dow) & (fb$page.total.likes <= input$no.likes),]
    
    fb <- fb %>%
      mutate(lt.friend.imp.grp          =  ntile(fb$lt.friend.impressions,10)) %>%
      mutate(lt.post.engaged.users.grp  =  ntile(fb$lt.post.engaged.users,10)) %>%
      mutate(page.likes.grp             =  ntile(fb$page.total.likes,50))
    
    ggplot(fb, aes(lt.friend.imp.grp, lt.post.engaged.users.grp)) + 
      geom_tile(aes(fill = page.likes.grp), colour = "white") + 
      scale_fill_gradient2(low='white',mid='#f6edf2', high='#ae5084', 
                           name="Number of Likes Generated by the Post",
                           breaks = seq(1,50,1),
                           labels = c("Low",rep('',48),"high" )) + 
      heat.theme + 
      scale_y_continuous(breaks=c(1,9), labels=c("Low","High")) +
      scale_x_continuous(breaks=c(1,9), labels=c("Low","High")) +
      xlab("Lifetime Impressions from Friends Who Liked Post") +
      ylab("Lifetime Engaged Users Who Liked Post")
    
  })
  
  
  output$smallmult <- renderPlot({
    
    ggplot(data=subset(df, admission.name %in% input$admit.type), aes(x=group.var, y=pct.admit, fill=admission.name)) + 
      facet_wrap(~group.name, scales='free') +
      geom_bar(stat = "identity") +
      scale_fill_manual(values = trauma.pal, name="Admission Type") +
      facet.theme 
      })
  
  output$parallel <- renderPlot({
    
    fb <- fb %>%
      mutate(users             =  ntile(fb$lt.post.engaged.users,10)) %>%
      mutate(consumptions      =  ntile(fb$lt.post.consumptions,10)) %>%
      mutate(reach             =  ntile(fb$lt.post.reach,10)) %>%
      mutate(impressions       =  ntile(fb$lt.post.impressions,10))
    
    fb <- subset(fb, Type %in% input$post.type)
    ggparcoord(fb, c(20,21,22,23), groupColumn = 2, mapping=aes(color=Type)) + 
      scale_color_manual(values = brewer.pal(4,"Set1")) +
      xlab("Engagement Metric for Post") +
      ylab("Relative Value")
    

  })
})  
